CREATE TABLE [dbo].[DateFormIncarcare] (
    [Id]             INT           IDENTITY (1, 1) NOT NULL,
    [nr]             INT           NOT NULL,
    [platiti]        INT           NOT NULL,
    [numarInCuvinte] VARCHAR (100) NOT NULL,
    [plat]           VARCHAR (30) NOT NULL,
    [codPlat]        VARCHAR (13)  NOT NULL,
    [adresaPlat]     VARCHAR (66) NOT NULL,
    [ibanPlat]       VARCHAR (24)  NOT NULL,
    [bicPlat]        VARCHAR (8)  NOT NULL,
    [deLa]           VARCHAR (50)  NOT NULL,
    [angajament]     VARCHAR (12)  NOT NULL,
    [indicator]      VARCHAR (10)  NOT NULL,
    [codProgr]       VARCHAR (11)  NOT NULL,
    [benef]          VARCHAR (30) NOT NULL,
    [codBenef]       VARCHAR (13)  NOT NULL,
    [ibanBenef]      VARCHAR (24)  NOT NULL,
    [bicBenef]       VARCHAR (8)  NOT NULL,
    [la]             VARCHAR (50)  NOT NULL,
    [nrEvid]         VARCHAR (23)  NOT NULL,
    [reprez]         VARCHAR (70) NOT NULL,
    [dataEmit]       DATE          NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

